# -------------------------------------------------------------------------------------------------
# Do not change/remove.
# -------------------------------------------------------------------------------------------------
Version: 1

# -------------------------------------------------------------------------------------------------
# C'est le prefix utilisé avant les messages liés à la base de données.
# -------------------------------------------------------------------------------------------------
Prefix: '&b&lSolandra &f»'

# -------------------------------------------------------------------------------------------------
# Prefix utilisé avant les messages dans la console.
# -------------------------------------------------------------------------------------------------
Log_Prefix: '§7[§bSolandra-Hideout§7]§b'

# -------------------------------------------------------------------------------------------------
# Quelle LANGUE souhaitez-vous utiliser à partir du fichier localization/messages_LANGUAGE.yml ?
#
# Disponible : "fr" (français), vous pouvez également créer votre propre langue si vous le souhaitez !
# -------------------------------------------------------------------------------------------------
Locale: fr

# -------------------------------------------------------------------------------------------------
# Quels sont les alias de commande pour ce plugin ?
#
# La commande principale est "/fishing".
# -------------------------------------------------------------------------------------------------
Aliases: []